const option = [
    { value: "angular", label: "Angular" },
    { value: "androrid", label: "Androrid" },
    { value: "arduino", label: "Arduino" },
    { value: "bootstrape", label: "bootstrape" },
    { value: "c++", label: "c++" },
    { value: "css", label: "css" },
    { value: "nodeJS", label: "NodeJS" },
    { value: "javascript", label: "JavaScript" },
    { value: "php", label: "PHP" },
    { value: "python", label: "Python" },
    { value: "react", label: "React" },
    { value: "dark", label: "dark" },
    { value: "django", label: "django" },
    { value: "docker", label: "docker" },
    { value: "flutter", label: "flutter" },
    { value: "git", label: "git" },
    { value: "github", label: "github" },
    { value: "graphql", label: "graphql" },
    { value: "hasura", label: "hasura" },
    { value: "html", label: "html" },
    { value: "java", label: "java" },
    { value: "kotlin", label: "kotlin" },
    { value: "laravel", label: "laravel" },
    { value: "mysql", label: "mysql" },
    { value: "next.js", label: "next.js" },
    { value: "r", label: "r" },
    { value: "shell", label: "shell" },
    { value: "sql", label: "sql" },
    { value: "typescript", label: "typescript" },
    
  ];

  export default option;